server:
  port: 8080

logging:
  level.org.logbook: TRACE

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
